---

- name: "install packages"
  apt:
    name: "{{ container_systemd_package }}"
    update_cache: yes
    state: present
    

- name: "check systemd version"
  command: systemctl --version
  register: systemd_version
  changed_when: false
